title: Numrich Albrecht Klumpp (DEV)
description: Numrich Albrecht Klumpp Gesellschaft von Architekten mbH
url: "http://localhost.loc:4000" # the base hostname & protocol for your site
mode: dev
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed