title: Numrich Albrecht Klumpp Architekten
description: Numrich Albrecht Klumpp Gesellschaft von Architekten mbH
url: "" # the base hostname & protocol for your site
mode: dev
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed