title: Numrich Albrecht Klumpp (DEV)
description: Numrich Albrecht Klumpp Gesellschaft von Architekten mbH
url: "http://192.168.178.70:4000" # the base hostname & protocol for your site
mode: dev
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed